version: "3"

services:
  ms-watchlist:
    container_name: ms-watchlist
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"